[sdl]
fullscreen=false
fulldouble=false
output=surface
autolock=false
waitonerror=false
priority=higher,normal
[render]
frameskip=0
aspect=false
scaler=none
[dosbox]
title=peteshoot-build
machine=svga_s3
memsize=16
emssize=4
[cpu]
core=normal
cputype=386
cycles=30000
cycleup=100
cycledown=20
[dos]
xms=true
ems=true
umb=false
[int10]
wait-on-error=false
[autoexec]
mount c C:\Users\patri\pea-shoot\dos\c
mount -ro d C:\Users\patri\pea-shoot\tools\bc31
c:
set BCPATH=D:\
set PATH=D:\BIN;C:\;D:\BIN
set TEMP=C:\OUT
set TMP=C:\OUT